# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Clifford <- function(a, b, c, d, iterations = 1e7L, x0 = 0, y0 = 0) {
    .Call(`_StrangeAttractors_Clifford`, a, b, c, d, iterations, x0, y0)
}

deJong <- function(a, b, c, d, iterations = 1e7L, x0 = 0, y0 = 0) {
    .Call(`_StrangeAttractors_deJong`, a, b, c, d, iterations, x0, y0)
}

